### ISSUE TITLE
Usage examples.

### ISSUE THREAD

**Issue by ExtinctAmoeba** [robertlevonyan/AndroidKEx#2]
Hi, can You please show how we should use RecyclerView from **Dynamic layout extensions** ? 

**For example:** 

How I can define types?
` itemTypes = { position -> ... }           // declare types of items`

Or bind data in selected view?
` creator = { item, position -> ... },      // write to list binding logic inside this lambda
`

Thank you.

**Comment by robertlevonyan** [comment]
The documentation was wrong.
I've fixed it please check it.
